const PLAN_CODES = {
  FREE: "free",
  STARTER: "starter",
  GROWTH: "growth",
  BASIC: "basic",
  PRO: "pro",
  ENTERPRISE: "enterprise",
};

const UNLIMITED = Number.MAX_SAFE_INTEGER;

const PLAN_DEFINITIONS = {
  [PLAN_CODES.FREE]: {
    code: PLAN_CODES.FREE,
    name: "Free",
    monthlyPrice: 0,
    yearlyPrice: 0,
    invoiceMonthlyLimit: 20,
    shortDescription: "Forever free billing basics for a small business.",
    trialEligible: false,
    trialDays: 0,
    staffUserLimit: 1,
    customerLimit: 100,
    productLimit: 100,
    businessLimit: 1,
    locationLimit: 1,
    storageMbLimit: 256,
    apiMonthlyQuota: 0,
    inventoryAccess: false,
    purchasesAccess: false,
    expensesAccess: true,
    quotationsAccess: true,
    creditNotesAccess: false,
    salesReturnsAccess: false,
    reportsAccess: true,
    pdfTemplatesAccess: false,
    sharingAccess: false,
    communicationsAccess: false,
    whatsappMonthlyQuota: 0,
    advancedGstAccess: false,
    eInvoiceAccess: false,
    industryModulesAccess: false,
    orderManagementAccess: false,
    projectsTasksAccess: false,
    recurringBillingAccess: false,
    appointmentsSchedulingAccess: false,
    productionJobWorkAccess: false,
    batchExpiryAccess: false,
    dispatchFulfilmentAccess: false,
    documentsApprovalsAccess: false,
  },
  [PLAN_CODES.STARTER]: {
    code: PLAN_CODES.STARTER,
    name: "Starter",
    shortDescription: "More invoices, sharing, and small-team billing.",
    monthlyPrice: 999,
    yearlyPrice: 9990,
    trialEligible: false,
    trialDays: 0,
    invoiceMonthlyLimit: 250,
    staffUserLimit: 5,
    customerLimit: 1000,
    productLimit: 1000,
    businessLimit: 1,
    locationLimit: 1,
    storageMbLimit: 1024,
    apiMonthlyQuota: 0,
    inventoryAccess: true,
    purchasesAccess: true,
    expensesAccess: true,
    quotationsAccess: true,
    creditNotesAccess: true,
    salesReturnsAccess: true,
    reportsAccess: false,
    pdfTemplatesAccess: true,
    sharingAccess: true,
    communicationsAccess: true,
    whatsappMonthlyQuota: 100,
    advancedGstAccess: false,
    eInvoiceAccess: false,
    industryModulesAccess: false,
    orderManagementAccess: false,
    projectsTasksAccess: false,
    recurringBillingAccess: false,
    appointmentsSchedulingAccess: false,
    productionJobWorkAccess: false,
    batchExpiryAccess: false,
    dispatchFulfilmentAccess: false,
    documentsApprovalsAccess: false,
  },
  [PLAN_CODES.BASIC]: {
    code: PLAN_CODES.BASIC,
    name: "Basic",
    compatibilityAliasFor: PLAN_CODES.STARTER,
    monthlyPrice: 999,
    yearlyPrice: 9990,
    trialEligible: false,
    trialDays: 0,
    invoiceMonthlyLimit: 250,
    staffUserLimit: 5,
    customerLimit: 1000,
    productLimit: 1000,
    businessLimit: 1,
    locationLimit: 1,
    storageMbLimit: 1024,
    apiMonthlyQuota: 0,
    inventoryAccess: true,
    purchasesAccess: true,
    expensesAccess: true,
    quotationsAccess: true,
    creditNotesAccess: true,
    salesReturnsAccess: true,
    reportsAccess: false,
    pdfTemplatesAccess: true,
    sharingAccess: true,
    communicationsAccess: true,
    whatsappMonthlyQuota: 100,
    advancedGstAccess: false,
    eInvoiceAccess: false,
    industryModulesAccess: false,
    orderManagementAccess: false,
    projectsTasksAccess: false,
    recurringBillingAccess: false,
    appointmentsSchedulingAccess: false,
    productionJobWorkAccess: false,
    batchExpiryAccess: false,
    dispatchFulfilmentAccess: false,
    documentsApprovalsAccess: false,
  },
  [PLAN_CODES.GROWTH]: {
    code: PLAN_CODES.GROWTH,
    name: "Growth",
    shortDescription: "Inventory, purchases, reports, and growing teams.",
    monthlyPrice: 1799,
    yearlyPrice: 17990,
    trialEligible: false,
    trialDays: 0,
    invoiceMonthlyLimit: 1000,
    staffUserLimit: 10,
    customerLimit: 5000,
    productLimit: 5000,
    businessLimit: 1,
    locationLimit: 3,
    storageMbLimit: 5120,
    apiMonthlyQuota: 500,
    inventoryAccess: true,
    purchasesAccess: true,
    expensesAccess: true,
    quotationsAccess: true,
    creditNotesAccess: true,
    salesReturnsAccess: true,
    reportsAccess: true,
    pdfTemplatesAccess: true,
    sharingAccess: true,
    communicationsAccess: true,
    whatsappMonthlyQuota: 500,
    advancedGstAccess: true,
    eInvoiceAccess: false,
    industryModulesAccess: false,
    orderManagementAccess: true,
    projectsTasksAccess: true,
    recurringBillingAccess: false,
    appointmentsSchedulingAccess: true,
    productionJobWorkAccess: false,
    batchExpiryAccess: true,
    dispatchFulfilmentAccess: true,
    documentsApprovalsAccess: true,
  },
  [PLAN_CODES.PRO]: {
    code: PLAN_CODES.PRO,
    name: "Pro",
    shortDescription: "Advanced GST, e-invoice readiness, automation, and scale.",
    monthlyPrice: 2499,
    yearlyPrice: 24990,
    trialEligible: true,
    trialDays: 14,
    invoiceMonthlyLimit: 2000,
    staffUserLimit: 20,
    customerLimit: UNLIMITED,
    productLimit: UNLIMITED,
    businessLimit: 1,
    locationLimit: 10,
    storageMbLimit: 20480,
    apiMonthlyQuota: 5000,
    inventoryAccess: true,
    purchasesAccess: true,
    expensesAccess: true,
    quotationsAccess: true,
    creditNotesAccess: true,
    salesReturnsAccess: true,
    reportsAccess: true,
    pdfTemplatesAccess: true,
    sharingAccess: true,
    communicationsAccess: true,
    whatsappMonthlyQuota: 1000,
    advancedGstAccess: true,
    eInvoiceAccess: true,
    industryModulesAccess: false,
    orderManagementAccess: true,
    projectsTasksAccess: true,
    recurringBillingAccess: true,
    appointmentsSchedulingAccess: true,
    productionJobWorkAccess: true,
    batchExpiryAccess: true,
    dispatchFulfilmentAccess: true,
    documentsApprovalsAccess: true,
  },
  [PLAN_CODES.ENTERPRISE]: {
    code: PLAN_CODES.ENTERPRISE,
    name: "Enterprise",
    monthlyPrice: 9999,
    yearlyPrice: 99990,
    shortDescription: "Custom commercial plan for high-volume or self-hosted businesses.",
    trialEligible: false,
    trialDays: 0,
    invoiceMonthlyLimit: UNLIMITED,
    staffUserLimit: 9999,
    customerLimit: UNLIMITED,
    productLimit: UNLIMITED,
    businessLimit: UNLIMITED,
    locationLimit: UNLIMITED,
    storageMbLimit: UNLIMITED,
    apiMonthlyQuota: UNLIMITED,
    inventoryAccess: true,
    purchasesAccess: true,
    expensesAccess: true,
    quotationsAccess: true,
    creditNotesAccess: true,
    salesReturnsAccess: true,
    reportsAccess: true,
    pdfTemplatesAccess: true,
    sharingAccess: true,
    communicationsAccess: true,
    whatsappMonthlyQuota: Number.MAX_SAFE_INTEGER,
    advancedGstAccess: true,
    eInvoiceAccess: true,
    industryModulesAccess: true,
    orderManagementAccess: true,
    projectsTasksAccess: true,
    recurringBillingAccess: true,
    appointmentsSchedulingAccess: true,
    productionJobWorkAccess: true,
    batchExpiryAccess: true,
    dispatchFulfilmentAccess: true,
    documentsApprovalsAccess: true,
  },
};

const PLAN_FEATURE_MAP = {
  inventory: "inventoryAccess",
  purchases: "purchasesAccess",
  expenses: "expensesAccess",
  quotations: "quotationsAccess",
  creditNotes: "creditNotesAccess",
  salesReturns: "salesReturnsAccess",
  reports: "reportsAccess",
  pdfTemplates: "pdfTemplatesAccess",
  sharing: "sharingAccess",
  communications: "communicationsAccess",
  advancedGst: "advancedGstAccess",
  eInvoice: "eInvoiceAccess",
  industryModules: "industryModulesAccess",
  orderManagement: "orderManagementAccess",
  projectsTasks: "projectsTasksAccess",
  recurringBilling: "recurringBillingAccess",
  appointmentsScheduling: "appointmentsSchedulingAccess",
  productionJobWork: "productionJobWorkAccess",
  batchExpiry: "batchExpiryAccess",
  dispatchFulfilment: "dispatchFulfilmentAccess",
  documentsApprovals: "documentsApprovalsAccess",
};

module.exports = {
  PLAN_CODES,
  PLAN_DEFINITIONS,
  PLAN_FEATURE_MAP,
};
